name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and pnpm with Volta
        uses: volta-cli/action@v4

      - name: Install node with Volta
        run: volta install node

      - name: Install pnpm with Volta
        run: volta install pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run format check
        run: pnpm run format

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
